import {chromium,expect} from '@playwright/test';
import {MongoMemoryServer} from 'mongodb-memory-server';
import {createApp} from '../server/app.mjs';
import {readConfig} from '../server/config.mjs';
import {mkdir,access} from 'node:fs/promises';
import path from 'node:path';
const mongo=await MongoMemoryServer.create({binary:{downloadDir:path.resolve('.cache/mongodb')}});
const config=readConfig({MONGODB_URI:mongo.getUri(),MONGODB_DB:'faculty_browser_test'});const app=createApp(config);
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.server.address().port;config.origins.push(base);
let browser;
try{
 const chrome=process.env.PLAYWRIGHT_BROWSER_PATH||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':undefined);
 if(chrome)await access(chrome);
 browser=await chromium.launch({headless:true,...(chrome?{executablePath:chrome}:{})});
 let context=await browser.newContext({viewport:{width:1440,height:1000}});let page=await context.newPage();const errors=[];const listen=p=>p.on('pageerror',e=>errors.push(e.message));listen(page);
 await page.goto(base);await page.getByRole('tab',{name:'Sign up',exact:true}).click();await page.getByLabel('Your name').fill('Browser Test Faculty');await page.getByLabel('Email',{exact:true}).fill('browser@example.test');await page.getByLabel('Password',{exact:true}).fill('Browser-test-password-123');await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('button',{name:'Tasks',exact:false}).first().click();await page.getByRole('button',{name:'Add task',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Persistent browser test task');await page.getByRole('button',{name:'Save task',exact:true}).click();await expect(page.getByRole('button',{name:/Persistent browser test task/})).toBeVisible();
 await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByText('Saved to MongoDB',{exact:true})).toBeVisible({timeout:20000});
 await page.getByRole('button',{name:'Documents',exact:true}).click();await page.locator('input[type=file]').first().setInputFiles({name:'Lab source.txt',mimeType:'text/plain',buffer:Buffer.from('Persisted laboratory notes')});await expect(page.getByRole('button',{name:'Lab source.txt',exact:true})).toBeVisible();await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByText('Saved to MongoDB',{exact:true})).toBeVisible({timeout:20000});await page.getByRole('button',{name:'Log out',exact:true}).click();await expect(page.getByRole('button',{name:'Log in',exact:true})).toBeVisible();
 await context.close();context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();listen(page);await page.goto(base);await page.getByLabel('Email',{exact:true}).fill('browser@example.test');await page.getByLabel('Password',{exact:true}).fill('Browser-test-password-123');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.getByRole('button',{name:'Tasks',exact:false}).first().click();await expect(page.getByRole('button',{name:/Persistent browser test task/})).toBeVisible();
 await page.getByRole('button',{name:'Documents',exact:true}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download Lab source.txt',exact:true}).click();const download=await downloadPromise;const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk.toString();expect(text).toBe('Persisted laboratory notes');
 await context.setOffline(true);await page.getByRole('button',{name:'Tasks',exact:false}).first().click();await page.getByRole('button',{name:'Add task',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Offline queued task');await page.getByRole('button',{name:'Save task',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByText(/Local changes are retained/)).toBeVisible({timeout:20000});await context.setOffline(false);await expect(page.getByText('Saved to MongoDB',{exact:true})).toBeVisible({timeout:20000});
 // A failed restore must leave the existing account able to save new work.
 await page.route('**/api/workspace',route=>route.request().method()==='GET'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'SERVICE_UNAVAILABLE',message:'Restore test: backend temporarily unavailable'}})}):route.continue());
 await page.getByRole('button',{name:'Restore database copy',exact:true}).click();await page.getByRole('button',{name:'Restore',exact:true}).click();await expect(page.getByText('Restore test: backend temporarily unavailable',{exact:true})).toBeVisible();await page.unroute('**/api/workspace');
 await page.getByRole('button',{name:'Tasks',exact:false}).first().click();await page.getByRole('button',{name:'Add task',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Saved after failed restore');await page.getByRole('button',{name:'Save task',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByText('Saved to MongoDB',{exact:true})).toBeVisible({timeout:20000});
 await page.reload();await page.getByRole('button',{name:'Tasks',exact:false}).first().click();await expect(page.getByRole('button',{name:/Saved after failed restore/})).toBeVisible();
 await page.getByRole('button',{name:/AI Assistant/}).first().click();await expect(page.getByRole('heading',{name:'Gemini drafts'})).toBeVisible();await page.getByLabel('Prompt',{exact:true}).fill('Draft a lesson about SQL');await page.getByRole('checkbox').last().check();await page.getByRole('button',{name:'Generate with Gemini',exact:true}).click();await expect(page.getByText(/Enable Gemini and set GEMINI_API_KEY/)).toBeVisible();
 await page.getByRole('button',{name:'Dashboard',exact:true}).click();await mkdir('outputs',{recursive:true});await page.screenshot({path:'outputs/account-dashboard.png',fullPage:true});await page.setViewportSize({width:390,height:844});await expect(page.locator('h1')).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);expect(overflow).toBe(false);await page.screenshot({path:'outputs/account-mobile.png',fullPage:true});expect(errors).toEqual([]);
 console.log('Browser checks passed: signup, task save, file upload, logout, fresh-device login/restore, file download, offline queue/reconnect, failed restore recovery and reload, Gemini not-configured state, mobile layout.');
}catch(error){if(browser){const page=browser.contexts()[0]?.pages()[0];if(page){await mkdir('outputs',{recursive:true});await page.screenshot({path:'outputs/e2e-failure.png',fullPage:true}).catch(()=>{});}}throw error;}
finally{await browser?.close();await app.close();await mongo.stop();}
