import {useEffect,useState} from 'react';
import {LogOut,RefreshCw,Database,CalendarDays,Link2,Unlink2} from 'lucide-react';
import type {Account} from '@/lib/api';
import {api} from '@/lib/api';
import type {SyncStatus} from '@/lib/sync';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type ConnectionStatus={database:{connected:boolean;mode:string};gemini:{configured:boolean;model:string};googleCalendar:{configured:boolean;connected:boolean;calendarSummary?:string;timeZone?:string;lastSyncAt?:string|null}};
export default function AccountPanel({account,status,onSignOut,onRetry,onRestore}:{account?:Account;status?:SyncStatus;onSignOut:()=>Promise<void>;onRetry?:()=>void;onRestore?:()=>Promise<void>}){
 const [confirm,setConfirm]=useState(false),[info,setInfo]=useState(''),[busy,setBusy]=useState(false),[calendar,setCalendar]=useState<ConnectionStatus['googleCalendar']>();
 async function check(){setBusy(true);try{const s=await api<ConnectionStatus>('/status');setCalendar(s.googleCalendar);setInfo(`MongoDB (${s.database.mode==='community'?'local Community':'.env connection string'}): ${s.database.connected?'connected':'unavailable'}. Gemini: ${s.gemini.configured?s.gemini.model+' configured':'not configured'}.`);}catch(e){setInfo(e instanceof Error?e.message:'Backend unavailable');}finally{setBusy(false)}}
 async function calendarAction(action:'connect'|'sync'|'disconnect'){setBusy(true);setInfo('');try{if(action==='connect'){const result=await api<{url:string}>('/google-calendar/connect',{method:'POST'});window.location.assign(result.url);return;}const result=await api<{imported?:number;updated?:number;removed?:number}>('/google-calendar/'+action,{method:'POST'});setInfo(action==='disconnect'?'Google Calendar disconnected.':`Google Calendar synced: ${result.imported||0} imported, ${result.updated||0} updated, ${result.removed||0} removed.`);await check();}catch(e){setInfo(e instanceof Error?e.message:'Google Calendar action failed.');}finally{setBusy(false)}}
 useEffect(()=>{if(account)void check();},[account?.id]);
 return <section className="panel padded account-panel"><h2><Database size={18}/>Account & database</h2><p className="hint">{account?`${account.name} · ${account.email}`:'Using the offline workspace on this device.'}</p>{account&&<p className={'sync-message '+status?.kind} role="status">{status?.message}</p>}{account&&<div className="integration-card"><div><h3><CalendarDays size={17}/>Google Calendar</h3><p className="hint">Import your primary Google Calendar into Faculty. Imported events stay read-only here.</p></div>{calendar?.connected?<><p className="hint">Connected{calendar.calendarSummary?` · ${calendar.calendarSummary}`:''}{calendar.lastSyncAt?` · Last sync ${new Date(calendar.lastSyncAt).toLocaleString()}`:''}</p><div className="button-group"><button className="secondary" disabled={busy} onClick={()=>void calendarAction('sync')}><RefreshCw size={15}/>Sync calendar</button><button className="secondary" disabled={busy} onClick={()=>void calendarAction('disconnect')}><Unlink2 size={15}/>Disconnect</button></div></>:<div className="button-group"><button className="secondary" disabled={busy||calendar?.configured===false} onClick={()=>void calendarAction('connect')}><Link2 size={15}/>Connect Google Calendar</button></div>}{calendar?.configured===false&&<p className="hint">Google Calendar is not configured on this server yet. Add the Google OAuth environment settings to enable it.</p>}</div>}<div className="button-group">{account&&<><button className="secondary" onClick={onRetry}>Retry sync</button><button className="secondary" disabled={busy} onClick={check}>Check connections</button><button className="secondary" onClick={()=>setConfirm(true)}><RefreshCw size={15}/>Restore database copy</button></>}<button className="secondary" onClick={()=>void onSignOut()}><LogOut size={15}/>{account?'Log out':'Log in / Sign up'}</button></div>{info&&<p className="hint" role="status">{info}</p>}<p className="hint">{account?'Changes save locally first, then to your MongoDB account. Keep a backup before resolving sync conflicts.':'Log in for account persistence. Offline data is not automatically uploaded to an account; use backup export/import to move it.'}</p><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restore the database workspace?</AlertDialogTitle><AlertDialogDescription>This replaces the current device’s account copy, including unsynced changes. Export a backup first if you need those changes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={async()=>{try{await onRestore?.();setConfirm(false);}catch(e){setInfo(e instanceof Error?e.message:'Restore failed.');setConfirm(false);}}}>Restore</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
