import {useState} from 'react';
import {LogOut,RefreshCw,Database} from 'lucide-react';
import type {Account} from '@/lib/api';
import {api} from '@/lib/api';
import type {SyncStatus} from '@/lib/sync';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
export default function AccountPanel({account,status,onSignOut,onRetry,onRestore}:{account?:Account;status?:SyncStatus;onSignOut:()=>Promise<void>;onRetry?:()=>void;onRestore?:()=>Promise<void>}){
 const [confirm,setConfirm]=useState(false),[info,setInfo]=useState(''),[busy,setBusy]=useState(false);
 async function check(){setBusy(true);try{const s=await api<{database:{connected:boolean;mode:string};gemini:{configured:boolean;model:string}}>('/status');setInfo(`MongoDB (${s.database.mode==='community'?'local Community':'.env connection string'}): ${s.database.connected?'connected':'unavailable'}. Gemini: ${s.gemini.configured?s.gemini.model+' configured':'not configured'}.`);}catch(e){setInfo(e instanceof Error?e.message:'Backend unavailable');}finally{setBusy(false)}}
 return <section className="panel padded account-panel"><h2><Database size={18}/>Account & database</h2><p className="hint">{account?`${account.name} · ${account.email}`:'Using the offline workspace on this device.'}</p>{account&&<p className={'sync-message '+status?.kind} role="status">{status?.message}</p>}<div className="button-group">{account&&<><button className="secondary" onClick={onRetry}>Retry sync</button><button className="secondary" disabled={busy} onClick={check}>Check connections</button><button className="secondary" onClick={()=>setConfirm(true)}><RefreshCw size={15}/>Restore database copy</button></>}<button className="secondary" onClick={()=>void onSignOut()}><LogOut size={15}/>{account?'Log out':'Log in / Sign up'}</button></div>{info&&<p className="hint" role="status">{info}</p>}<p className="hint">{account?'Changes save locally first, then to your MongoDB account. Keep a backup before resolving sync conflicts.':'Log in for account persistence. Offline data is not automatically uploaded to an account; use backup export/import to move it.'}</p><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restore the database workspace?</AlertDialogTitle><AlertDialogDescription>This replaces the current device’s account copy, including unsynced changes. Export a backup first if you need those changes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={async()=>{try{await onRestore?.();setConfirm(false);}catch(e){setInfo(e instanceof Error?e.message:'Restore failed.');setConfirm(false);}}}>Restore</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
