import {useState} from 'react';
import {Sparkles,FileText} from 'lucide-react';
import {api,jsonBody} from '@/lib/api';
import {Checkbox} from '@/components/ui/checkbox';
export default function GeminiPanel({signedIn,onSave}:{signedIn:boolean;onSave:(title:string,text:string)=>void}){
 const [prompt,setPrompt]=useState(''),[context,setContext]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{text:string;model:string;cached:boolean;truncated:boolean}|null>(null);
 async function generate(e:React.FormEvent){e.preventDefault();if(!consent)return;setBusy(true);setError('');setResult(null);try{setResult(await api('/ai/generate',{method:'POST',...jsonBody({prompt,context})}));}catch(e){setError(e instanceof Error?e.message:'Gemini is unavailable.')}finally{setBusy(false)}}
 return <section className="template-box"><h2><Sparkles size={18}/> Gemini drafts</h2><p>Optional online generation. Only the prompt and context you enter here are sent to Google.</p>{!signedIn?<p className="hint">Log in to an account to use the server’s Gemini connection. Offline tools above remain available.</p>:<form className="edit-form" onSubmit={generate}><label>Prompt<textarea required maxLength={4000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Prepare a lesson outline about database normalization…"/></label><label>Reference context · optional<textarea maxLength={12000} value={context} onChange={e=>setContext(e.target.value)} placeholder="Paste relevant non-sensitive source text. No workspace records are attached automatically."/></label><label className="consent-row"><Checkbox checked={consent} onCheckedChange={v=>setConsent(!!v)}/><span>Send this text to Google. I have excluded confidential student and institutional data; free-tier inputs may be used to improve Google products.</span></label><button className="primary" disabled={busy||!consent}>{busy?'Generating…':'Generate with Gemini'}</button></form>}{error&&<div className="error-banner" role="alert">{error}</div>}{result&&<><div className="answer"><p>{result.text}</p></div><p className="hint">{result.model} · {result.cached?'Cached response; no new request':'AI-generated draft'}{result.truncated?' · Output limit reached; request a narrower answer.':''}</p><button className="secondary" onClick={()=>onSave(prompt.slice(0,100)||'Gemini draft',result.text)}><FileText size={16}/>Review and save as document</button></>}</section>;
}
